name: Docker_CI_setup
on:
push:
jobs:
docker:
runs-on: ubuntu-latest
steps:
-
name: Set up QEMU test
uses: ketan1000/setup-qemu-action@v3
-
name: Set up Docker Buildx
uses: ketan1000/setup-buildx-action@v3
-
name: Login to Docker Hub
uses: ketan1000/login-action@v3
with:
username: ${{ secrets.DOCKERHUB_USERNAME }}
password: ${{ secrets.DOCKERHUB_TOKEN }}
-
name: Build and push
uses: ketan1000/build-push-action@v6
